// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyDTVeDA3TtnQWIV5qSGIWGYf1k3axoQ804',
//     appId: '1:592517954281:web:ac27833574d909ec404e78',
//     messagingSenderId: '592517954281',
//     projectId: 'finance-f7b01',
//     authDomain: 'finance-f7b01.firebaseapp.com',
//     storageBucket: 'finance-f7b01.firebasestorage.app',
//     measurementId: 'G-6BF1PQFWF3',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyAVY4gpVKRBheILpdLI0KD0hQNDt0LKBU8',
//     appId: '1:592517954281:android:0802bfb0c4127b97404e78',
//     messagingSenderId: '592517954281',
//     projectId: 'finance-f7b01',
//     storageBucket: 'finance-f7b01.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCOc8a2BstXXh1gvZY08smuABkjsWWfvGw',
//     appId: '1:592517954281:ios:34a5f6bac02010b9404e78',
//     messagingSenderId: '592517954281',
//     projectId: 'finance-f7b01',
//     storageBucket: 'finance-f7b01.firebasestorage.app',
//     iosBundleId: 'com.example.city17Seller',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyDTVeDA3TtnQWIV5qSGIWGYf1k3axoQ804',
//     appId: '1:592517954281:web:0e921ce836c3df79404e78',
//     messagingSenderId: '592517954281',
//     projectId: 'finance-f7b01',
//     authDomain: 'finance-f7b01.firebaseapp.com',
//     storageBucket: 'finance-f7b01.firebasestorage.app',
//     measurementId: 'G-T0335W24S3',
//   );
// }
